export const JsonList = [
    {
      "Number": 1,
      "Name": "Kutuzov Hold",
      "CardType": "HQ",
      "Faction": "Awaken",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Legendary",
      "id": "OTK001",
      "Description": "[End step]: If General Planning is 0, your most wounded ally Heals 12."
    },
    {
      "Number": 2,
      "Name": "Dogana",
      "CardType": "HQ",
      "Faction": "Entropy",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Legendary",
      "id": "OTK002",
      "Description": "Whenever an ally [Dies], your Entropy Techs get +1 RES."
    },
    {
      "Number": 3,
      "Name": "The Elephant",
      "CardType": "HQ",
      "Faction": "Inhuman",
      "Artist": "Carlos Moreno",
      "Rarity": "Legendary",
      "id": "OTK003",
      "Description": "Whenever an ally [Dies], deal 2xInhuman damage to the rightmost foe."
    },
    {
      "Number": 4,
      "Name": "OS Ares",
      "CardType": "HQ",
      "Faction": "Owner",
      "Artist": "Gonzo Snow",
      "Rarity": "Legendary",
      "id": "OTK004",
      "Description": "Armed allies get Grip and +4xRES ATK.\nLeftmost armed Owner ally gets Toughness 2."
    },
    {
      "Number": 5,
      "Name": "Stoneward",
      "CardType": "HQ",
      "Faction": "Awaken",
      "Artist": "Gonzo Snow",
      "Rarity": "Legendary",
      "id": "OTK005",
      "Description": "As long as you have exactly 1 Awaken ally and they have no planning, they get +40/+40."
    },
    {
      "Number": 6,
      "Name": "Reene's",
      "CardType": "HQ",
      "Faction": "Entropy",
      "Artist": "Daniel Vega",
      "Rarity": "Legendary",
      "id": "OTK006",
      "Description": "Whenever an ally Riots, they get +8 ATK."
    },
    {
      "Number": 7,
      "Name": "Sand Abbey",
      "CardType": "HQ",
      "Faction": "Inhuman",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Legendary",
      "id": "OTK007",
      "Description": "Whenever an ally Frightens, they get +8 ATK."
    },
    {
      "Number": 8,
      "Name": "WPD Comms Inc.",
      "CardType": "HQ",
      "Faction": "Owner",
      "Artist": "Javier Bahamonde",
      "Rarity": "Legendary",
      "id": "OTK008",
      "Description": "[Draw step]: If General Planning is 0, deal Owner damage to the leftmost foe."
    },
    {
      "Number": 9,
      "Name": "Attentio Prima",
      "CardType": "HQ",
      "Faction": "Awaken",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Legendary",
      "id": "OTK009",
      "Description": "Whenever a foe [Dies], your armed Awaken allies get +20 HP."
    },
    {
      "Number": 10,
      "Name": "Alexandria",
      "CardType": "HQ",
      "Faction": "Entropy",
      "Artist": "Daniel Vega",
      "Rarity": "Legendary",
      "id": "OTK010",
      "Description": "[End step]: If General Planning is 0, your Entropy ally with the lowest HP gets +8 ATK."
    },
    {
      "Number": 11,
      "Name": "Binder Tattoo Studio",
      "CardType": "HQ",
      "Faction": "Inhuman",
      "Artist": "Daniel Vega",
      "Rarity": "Legendary",
      "id": "OTK011",
      "Description": "[End step]:  If General Planning is 0, armed Inhuman allies get +Inhuman ATK."
    },
    {
      "Number": 12,
      "Name": "The Unifier",
      "CardType": "HQ",
      "Faction": "Owner",
      "Artist": "Gonzo Snow",
      "Rarity": "Legendary",
      "id": "OTK012",
      "Description": "Your allies get Toughness 3."
    },
    {
      "Number": 13,
      "Name": "Ouroboros",
      "CardType": "Character",
      "Faction": "Awaken",
      "Gender": "Male",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Legendary",
      "id": "OTK013",
      "Description": "(Loyal): Awaken allies get Toughness 7.\n[Dev step]: Other Awaken allies Heal 10."
    },
    {
      "Number": 14,
      "Name": "Casemira Kutuzov",
      "CardType": "Character",
      "Faction": "Awaken",
      "Gender": "Female",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Legendary",
      "id": "OTK014",
      "Description": "(Loyal)[Struck]: Hit leftmost opposing Tech once.\n(Slot <3)[Draw step]: Gets +5xAwaken ATK.\n"
    },
    {
      "Number": 15,
      "Name": "Elena Davre",
      "CardType": "Character",
      "Faction": "Awaken",
      "Gender": "Female",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Legendary",
      "id": "OTK015",
      "Description": "(Entropy 1): Gets +62 ATK.\n(Inhuman 1): Gets Toughness 21.\n(Owner 1): Gets +120 HP."
    },
    {
      "Number": 16,
      "Name": "Sredoje Petrovi\u0107",
      "CardType": "Character",
      "Faction": "Awaken",
      "Gender": "Male",
      "Artist": "Gonzo Snow",
      "Rarity": "Legendary",
      "id": "OTK016",
      "Description": "Toughness 32.\n[Arrive]: Swaps with your most wounded ally."
    },
    {
      "Number": 17,
      "Name": "Stonehand",
      "CardType": "Character",
      "Faction": "Awaken",
      "Gender": "Male",
      "Artist": "Gonzo Snow",
      "Rarity": "Legendary",
      "id": "OTK017",
      "Description": "(Slot>2) [Arrive]: Deals 120 damage to rival."
    },
    {
      "Number": 18,
      "Name": "Breeze",
      "CardType": "Character",
      "Faction": "Entropy",
      "Gender": "Female",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Legendary",
      "id": "OTK018",
      "Description": "Grip. Toughness 3x[F].\n(Slot<3)[Kill]: Rightmost ally Riots 2 to the right."
    },
    {
      "Number": 19,
      "Name": "Namonaki Yuki",
      "CardType": "Character",
      "Faction": "Entropy",
      "Gender": "Male",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Legendary",
      "id": "OTK019",
      "Description": "Grip. Toughness 12.\n(Loyal): Rival gets -55 HP."
    },
    {
      "Number": 20,
      "Name": "Florencia Wolff",
      "CardType": "Character",
      "Faction": "Entropy",
      "Gender": "Female",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Legendary",
      "id": "OTK020",
      "Description": "(HP>35%)[Attack]: Hit the leftmost opposing Tech. Repeat."
    },
    {
      "Number": 21,
      "Name": "San Amaro",
      "CardType": "Character",
      "Faction": "Entropy",
      "Gender": "Male",
      "Artist": "Gonzo Snow",
      "Rarity": "Legendary",
      "id": "OTK021",
      "Description": "(Armed & HP>51%)[Attack]: Assigned Tech gets +2 RES.\n[Attack]: Ally to the right gets +12 HP."
    },
    {
      "Number": 22,
      "Name": "Chaski",
      "CardType": "Character",
      "Faction": "Entropy",
      "Gender": "Male",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Legendary",
      "id": "OTK022",
      "Description": "(Slot >2): Rival gets -30 ATK.\n[Draw step]: Gets +3xEntropy ATK."
    },
    {
      "Number": 23,
      "Name": "Azrael",
      "CardType": "Character",
      "Faction": "Inhuman",
      "Gender": "Non Binary",
      "Artist": "Mat\u00edas Cabezas",
      "Rarity": "Legendary",
      "id": "OTK023",
      "Description": "Toughness 20.\n(Armed): Other allies get (+4/+4)xRES."
    },
    {
      "Number": 24,
      "Name": "Von Koenig",
      "CardType": "Character",
      "Faction": "Inhuman",
      "Gender": "Male",
      "Artist": "Daniel Vega",
      "Rarity": "Legendary",
      "id": "OTK024",
      "Description": "Grip. Toughness 4xInhuman.\n(Armed): Gets +4xInhuman ATK."
    },
    {
      "Number": 25,
      "Name": "Al\u00e9c Binder",
      "CardType": "Character",
      "Faction": "Inhuman",
      "Gender": "Male",
      "Artist": "Javiera D\u00edaz",
      "Rarity": "Legendary",
      "id": "OTK025",
      "Description": "(HP>28%): [NB] allies get +10x[NB] ATK."
    },
    {
      "Number": 26,
      "Name": "Khaldun",
      "CardType": "Character",
      "Faction": "Inhuman",
      "Gender": "Non Binary",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Legendary",
      "id": "OTK026",
      "Description": "Berserk. Toughness 12.\n[Arrive]: Rival gets -25 ATK. Then, Frightens rival."
    },
    {
      "Number": 27,
      "Name": "Nightress",
      "CardType": "Character",
      "Faction": "Inhuman",
      "Gender": "Female",
      "Artist": "Sara Contreras",
      "Rarity": "Legendary",
      "id": "OTK027",
      "Description": "Grip. Toughness [F]xInhuman.\nGets +12x[F] ATK."
    },
    {
      "Number": 28,
      "Name": "C",
      "CardType": "Character",
      "Faction": "Owner",
      "Gender": "Male",
      "Artist": "Gonzo Snow",
      "Rarity": "Legendary",
      "id": "OTK028",
      "Description": "(Inhuman 1): Toughness 20.\n(Entropy 1): Gets +40/+80.\n(Awaken 1)[End step]: Other allies Heal 17."
    },
    {
      "Number": 29,
      "Name": "Pauline Weber",
      "CardType": "Character",
      "Faction": "Owner",
      "Gender": "Female",
      "Artist": "Gonzo Snow",
      "Rarity": "Legendary",
      "id": "OTK029",
      "Description": "[Arrive] or [Attack]: Your most wounded [F] ally, excluding Pauline Weber, Heals 20."
    },
    {
      "Number": 30,
      "Name": "Johnny Patriot",
      "CardType": "Character",
      "Faction": "Owner",
      "Gender": "Male",
      "Artist": "Genzo",
      "Rarity": "Legendary",
      "id": "OTK030",
      "Description": "(Loyal): Toughness 9.\n[Attack]: The foe with the highest ATK Obeys."
    },
    {
      "Number": 31,
      "Name": "William Abioye",
      "CardType": "Character",
      "Faction": "Owner",
      "Gender": "Male",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Legendary",
      "id": "OTK031",
      "Description": "(Slot <3): Gets +7xOwner ATK.\n(HP>72%)[Fight step]: The foe with the lowest ATK Obeys."
    },
    {
      "Number": 32,
      "Name": "Dominika Dudek",
      "CardType": "Character",
      "Faction": "Owner",
      "Gender": "Female",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Legendary",
      "id": "OTK032",
      "Description": "[Struck]: Deals 9+Awaken+Entropy to the most wounded foe.\n[Kill]: Leftmost Owner ally Heals 60."
    },
    {
      "Number": 33,
      "Name": "Spilling Nick",
      "CardType": "Character",
      "Faction": "Awaken",
      "Gender": "Male",
      "Artist": "Felipe Araya",
      "Rarity": "Rare",
      "id": "OTK033",
      "Description": "(Awaken 3)[Attack]: Deals 12 damage to rival and adjacent foes."
    },
    {
      "Number": 34,
      "Name": "Claw",
      "CardType": "Character",
      "Faction": "Awaken",
      "Gender": "Non Binary",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Rare",
      "id": "OTK034",
      "Description": "(Armed): Grip. Gets +44/+33\n[Pick-up]: Swaps with your rightmost ally. Then, Frightens rival."
    },
    {
      "Number": 35,
      "Name": "Mar\u00eda del Tr\u00e1nsito",
      "CardType": "Character",
      "Faction": "Awaken",
      "Gender": "Female",
      "Artist": "Tae Valenzuela",
      "Rarity": "Rare",
      "id": "OTK035",
      "Description": "Toughness 6+[F]. Whenever an ally [Dies], Mar\u00eda del Tr\u00e1nsito deals 6x[F] damage to the opposing HQ."
    },
    {
      "Number": 36,
      "Name": "Hadrianus",
      "CardType": "Character",
      "Faction": "Awaken",
      "Gender": "Male",
      "Artist": "Dreg",
      "Rarity": "Rare",
      "id": "OTK036",
      "Description": "Hadrianus and the ally to his left both get +6xAwaken ATK."
    },
    {
      "Number": 37,
      "Name": "Thanata",
      "CardType": "Character",
      "Faction": "Awaken",
      "Gender": "Female",
      "Artist": "Dreg",
      "Rarity": "Rare",
      "id": "OTK037",
      "Description": "As long as Thanata has no rival, she gets +43 ATK.\n[Arrive]: Frightens rival."
    },
    {
      "Number": 38,
      "Name": "Santiago Pieldelobo",
      "CardType": "Character",
      "Faction": "Awaken",
      "Gender": "Male",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Rare",
      "id": "OTK038",
      "Description": "Toughness 10.\nRival gets -6xAwaken ATK."
    },
    {
      "Number": 39,
      "Name": "Fazir",
      "CardType": "Character",
      "Faction": "Awaken",
      "Gender": "Male",
      "Artist": "Javier Bahamonde",
      "Rarity": "Rare",
      "id": "OTK039",
      "Description": "(Slot <3): Gets Toughness 8 and +95 HP.\n(Slot>1)[End step]: Swaps with the ally to his left and deals 15 damage to the leftmost foe."
    },
    {
      "Number": 40,
      "Name": "Marduk Urshan",
      "CardType": "Character",
      "Faction": "Entropy",
      "Gender": "Non Binary",
      "Artist": "Gonzo Snow",
      "Rarity": "Rare",
      "id": "OTK040",
      "Description": "Grip. Toughness 12+Entropy.\n(Armed): Gets +124 HP."
    },
    {
      "Number": 41,
      "Name": "Dusk",
      "CardType": "Character",
      "Faction": "Entropy",
      "Gender": "Female",
      "Artist": "Alexia O\u00f1ate",
      "Rarity": "Rare",
      "id": "OTK041",
      "Description": "\n[End step]: Gets +2x[F] ATK. This ability triggers even if Dusk is not Ready."
    },
    {
      "Number": 42,
      "Name": "The Bannerwasps",
      "CardType": "Character",
      "Faction": "Entropy",
      "Gender": "Non Binary",
      "Artist": "Irma Matus",
      "Rarity": "Rare",
      "id": "OTK042",
      "Description": "(NB 3): Gets +42 ATK.\n(Loyal)[Fight step]: Rightmost ally Riots 2 to the right."
    },
    {
      "Number": 43,
      "Name": "Lucio Fern\u00e1ndez",
      "CardType": "Character",
      "Faction": "Entropy",
      "Gender": "Male",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Rare",
      "id": "OTK043",
      "Description": "(Slot 1): Gets Toughness 17 and +100 HP.\n(Armed)[End step]: Your other [M] allies Heal 11xRES."
    },
    {
      "Number": 44,
      "Name": "Artaxerxes",
      "CardType": "Character",
      "Faction": "Entropy",
      "Gender": "Male",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Rare",
      "id": "OTK044",
      "Description": "[Arrive]: Deals 80 damage to the leftmost foe.\n(Slot >2): Gets Toughness 8xEntropy."
    },
    {
      "Number": 45,
      "Name": "Mangoose",
      "CardType": "Character",
      "Faction": "Entropy",
      "Gender": "Female",
      "Artist": "Daniel Vega",
      "Rarity": "Rare",
      "id": "OTK045",
      "Description": "(Loyal)[Arrive]: Frightens foe in Slot 1. \n[Arrive] or [Dies]: Your leftmost Entropy ally Heals 60."
    },
    {
      "Number": 46,
      "Name": "Hyun-ki",
      "CardType": "Character",
      "Faction": "Entropy",
      "Gender": "Female",
      "Artist": "Rowein",
      "Rarity": "Rare",
      "id": "OTK046",
      "Description": "Toughness 18.\nAs long as ally to the right is [F], Hyun-ki and her both get +30 ATK."
    },
    {
      "Number": 47,
      "Name": "Ulfhild",
      "CardType": "Character",
      "Faction": "Inhuman",
      "Gender": "Male",
      "Artist": "Thor",
      "Rarity": "Rare",
      "id": "OTK047",
      "Description": "Berserk. Toughness 16.\nGets +10x[M] HP."
    },
    {
      "Number": 48,
      "Name": "Landv\u00e6ttir",
      "CardType": "Character",
      "Faction": "Inhuman",
      "Gender": "Male",
      "Artist": "Sara Contreras",
      "Rarity": "Rare",
      "id": "OTK048",
      "Description": "Grip. Toughness 18.\n(Armed): Gets + 15*RES ATK."
    },
    {
      "Number": 49,
      "Name": "Epsilon",
      "CardType": "Character",
      "Faction": "Inhuman",
      "Gender": "Non Binary",
      "Artist": "Thor",
      "Rarity": "Rare",
      "id": "OTK049",
      "Description": "Rival gets -13xEntropy HP and -9xOwner ATK."
    },
    {
      "Number": 50,
      "Name": "Murder of Crows",
      "CardType": "Character",
      "Faction": "Inhuman",
      "Gender": "Non Binary",
      "Artist": "Patricio Araya",
      "Rarity": "Rare",
      "id": "OTK050",
      "Description": "[Attack]: Other [NB] allies Heal 9.\n[Kill]: Deals 10x[NB] damage to the opposing HQ."
    },
    {
      "Number": 51,
      "Name": "Colonel Galkin",
      "CardType": "Character",
      "Faction": "Inhuman",
      "Gender": "Female",
      "Artist": "Noelia V\u00e9liz",
      "Rarity": "Rare",
      "id": "OTK051",
      "Description": "Berserk.\n[Attack]: Gets +3xInhuman ATK."
    },
    {
      "Number": 52,
      "Name": "Cleo Pierce",
      "CardType": "Character",
      "Faction": "Inhuman",
      "Gender": "Female",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Rare",
      "id": "OTK052",
      "Description": "Toughness 8+[F]+Inhuman.\n(Inhuman 3)[Arrive]: Frightens rival."
    },
    {
      "Number": 53,
      "Name": "Gustav Bilyk",
      "CardType": "Character",
      "Faction": "Inhuman",
      "Gender": "Male",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Rare",
      "id": "OTK053",
      "Description": "Toughness 21.\n[Dies]: Deals 80 damage to the healthiest foe."
    },
    {
      "Number": 54,
      "Name": "Alia Oz",
      "CardType": "Character",
      "Faction": "Owner",
      "Gender": "Female",
      "Artist": "Daniel Vega",
      "Rarity": "Rare",
      "id": "OTK054",
      "Description": "(Loyal): Up to 3 allies to the left get +13 ATK."
    },
    {
      "Number": 55,
      "Name": "Admiral Galazzio",
      "CardType": "Character",
      "Faction": "Owner",
      "Gender": "Male",
      "Artist": "Daniel Vega",
      "Rarity": "Rare",
      "id": "OTK055",
      "Description": "(Loyal): Toughness 6.\n[Kill]: Gets +40 HP and Owners allies get +10 ATK."
    },
    {
      "Number": 56,
      "Name": "Three Fists",
      "CardType": "Character",
      "Faction": "Owner",
      "Gender": "Male",
      "Artist": "Daniel Vega",
      "Rarity": "Rare",
      "id": "OTK056",
      "Description": "Toughness 5xOwner.\n(Slot 1): As long as rival has Basic Attack Type, they get -15 ATK."
    },
    {
      "Number": 57,
      "Name": "General Tanaka",
      "CardType": "Character",
      "Faction": "Owner",
      "Gender": "Female",
      "Artist": "Javiera D\u00edaz",
      "Rarity": "Rare",
      "id": "OTK057",
      "Description": "(Loyal & Slot <3): Gets +37 ATK.\n[Arrive]: Healthiest opponent Obeys. Then, Tanaka deals 50 damage to her rival."
    },
    {
      "Number": 58,
      "Name": "Isabel Bennett",
      "CardType": "Character",
      "Faction": "Owner",
      "Gender": "Female",
      "Artist": "Daniel Vega",
      "Rarity": "Rare",
      "id": "OTK058",
      "Description": "(Loyal)[Arrive]: Your leftmost Owner Tech gets +1 RES.\n[Arrive]: Leftmost ally Heals 100."
    },
    {
      "Number": 59,
      "Name": "Ilyich",
      "CardType": "Character",
      "Faction": "Owner",
      "Gender": "Male",
      "Artist": "Isabel Bennett",
      "Rarity": "Rare",
      "": " ",
      "id": "OTK059",
      "Description": "(Slot 1): Toughness 24.\n[Arrive]: Rival Obeys.\n"
    },
    {
      "Number": 60,
      "Name": "Spider Wolff",
      "CardType": "Character",
      "Faction": "Owner",
      "Gender": "Male",
      "Artist": "Genzo",
      "Rarity": "Rare",
      "id": "OTK060",
      "Description": "Toughness 4xOwner.\n(Owner 3): Adjacent allies get +24 ATK."
    },
    {
      "Number": 61,
      "Name": "El-Baz",
      "CardType": "Character",
      "Faction": "Awaken",
      "Gender": "Male",
      "Artist": "Gustavo Lara",
      "Rarity": "Uncommon",
      "id": "OTK061",
      "Description": "(Awaken 3): Ally to the right gets +120 HP."
    },
    {
      "Number": 62,
      "Name": "The Warren",
      "CardType": "Character",
      "Faction": "Awaken",
      "Gender": "Non Binary",
      "Artist": "Mat\u00edas Cabezas",
      "Rarity": "Uncommon",
      "id": "OTK062",
      "Description": "Toughness 8+[NB]. Gets +7x[NB] ATK.\n[Arrive]: Swaps with ally with the lowest ATK."
    },
    {
      "Number": 63,
      "Name": "Dr. Lee Park",
      "CardType": "Character",
      "Faction": "Awaken",
      "Gender": "Female",
      "Artist": "Patricio Araya",
      "Rarity": "Uncommon",
      "id": "OTK063",
      "Description": "Dr. Lee Park's base ATK is equal to her rival's, if any."
    },
    {
      "Number": 64,
      "Name": "Sadiq",
      "CardType": "Character",
      "Faction": "Awaken",
      "Gender": "Male",
      "Artist": "Jos\u00e9 Huicham\u00e1n",
      "Rarity": "Uncommon",
      "id": "OTK064",
      "Description": "Other leftmost Awaken ally gets (+30/+20).\n(Loyal): Toughness 28."
    },
    {
      "Number": 65,
      "Name": "Poncho & Montgomery",
      "CardType": "Character",
      "Faction": "Awaken",
      "Gender": "Male",
      "Artist": "Felipe Araya",
      "Rarity": "Uncommon",
      "id": "OTK065",
      "Description": "(M 3): Gets Toughness 13.\n(HP<53%)[Draw step]: Heals 12."
    },
    {
      "Number": 66,
      "Name": "Ava Nasseri",
      "CardType": "Character",
      "Faction": "Awaken",
      "Gender": "Female",
      "Artist": "Alexia O\u00f1ate",
      "Rarity": "Uncommon",
      "id": "OTK066",
      "Description": "(Loyal): Gets +80/-40."
    },
    {
      "Number": 67,
      "Name": "Sofia Dunn",
      "CardType": "Character",
      "Faction": "Entropy",
      "Gender": "Female",
      "Artist": "Daniel Vega",
      "Rarity": "Uncommon",
      "id": "OTK067",
      "Description": "(Loyal & Entropy 3): Toughness 3xEntropy.\n[Kill]: Heals 60."
    },
    {
      "Number": 68,
      "Name": "Falstaff",
      "CardType": "Character",
      "Faction": "Entropy",
      "Gender": "Male",
      "Artist": "Sara Contreras",
      "Rarity": "Uncommon",
      "id": "OTK068",
      "Description": "(Loyal): Gets Toughness 27.\n[Pick-up]: Deals 38 damage to rival and gets +8 ATK."
    },
    {
      "Number": 69,
      "Name": "Mitrovic",
      "CardType": "Character",
      "Faction": "Entropy",
      "Gender": "Male",
      "Artist": "Gonzo Snow",
      "Rarity": "Uncommon",
      "id": "OTK069",
      "Description": "Toughness Entropyx[M].\n[Arrive]: Hit the opposing Tech in Mitrovic's Slot 3 times.\n"
    },
    {
      "Number": 70,
      "Name": "Rashkov",
      "CardType": "Character",
      "Faction": "Entropy",
      "Gender": "Male",
      "Artist": "Daniel Vega",
      "Rarity": "Uncommon",
      "id": "OTK070",
      "Description": "Foes with Ranged Attack Type get -18 ATK.\n(HP<42%): Gets Toughness 8."
    },
    {
      "Number": 71,
      "Name": "Hendrickson",
      "CardType": "Character",
      "Faction": "Entropy",
      "Gender": "Male",
      "Artist": "Gonzo Snow",
      "Rarity": "Uncommon",
      "id": "OTK071",
      "Description": "Gets +15 ATK for each M foe.\n(Loyal): Gets +18xEntropy HP."
    },
    {
      "Number": 72,
      "Name": "Nasrin",
      "CardType": "Character",
      "Faction": "Entropy",
      "Gender": "Female",
      "Artist": "Ra\u00fal Maldonado Ikkitouch",
      "Rarity": "Uncommon",
      "id": "OTK072",
      "Description": "Gets +2xEntropyxOwner ATK.\n(Armed)[Attack]: Gets +4xRES ATK."
    },
    {
      "Number": 73,
      "Name": "Finn",
      "CardType": "Character",
      "Faction": "Inhuman",
      "Gender": "Male",
      "Artist": "Dreg",
      "Rarity": "Uncommon",
      "id": "OTK073",
      "Description": "Toughness 22.\n[Kill]: Heals 54."
    },
    {
      "Number": 74,
      "Name": "Lara Domain",
      "CardType": "Character",
      "Faction": "Inhuman",
      "Gender": "Female",
      "Artist": "Daniel Vega",
      "Rarity": "Uncommon",
      "id": "OTK074",
      "Description": "Berserk.\n[Struck]: Deals 8x[F] damage to the rival.\n[Kill]: Heal 69. "
    },
    {
      "Number": 75,
      "Name": "Yui Koumoto",
      "CardType": "Character",
      "Faction": "Inhuman",
      "Gender": "Female",
      "Artist": "Genzo",
      "Rarity": "Uncommon",
      "id": "OTK075",
      "Description": "Toughnes 5+[F]+Inhuman.\n[Attack]: Deals 20+[F]xInhuman damage to the opposing HQ."
    },
    {
      "Number": 76,
      "Name": "Moody Mary",
      "CardType": "Character",
      "Faction": "Inhuman",
      "Gender": "Non Binary",
      "Artist": "Javiera D\u00edaz",
      "Rarity": "Uncommon",
      "id": "OTK076",
      "Description": "Berserk.\n(HP<77%)[Attack]: Heal 13.\n"
    },
    {
      "Number": 77,
      "Name": "Grunting Grunts",
      "CardType": "Character",
      "Faction": "Inhuman",
      "Gender": "Male",
      "Artist": "Dreg",
      "Rarity": "Uncommon",
      "id": "OTK077",
      "Description": "Berserk. \n(Inhuman 3): Gets (+4/+10)xInhuman.\n(Loyal)[Kill]: Inhuman allies get +12 ATK."
    },
    {
      "Number": 78,
      "Name": "M\u00fcrag",
      "CardType": "Character",
      "Faction": "Inhuman",
      "Gender": "Male",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Uncommon",
      "id": "OTK078",
      "Description": "Toughness 36.\n(Loyal): Gets +8xInhuman ATK."
    },
    {
      "Number": 79,
      "Name": "Baranov",
      "CardType": "Character",
      "Faction": "Owner",
      "Gender": "Male",
      "Artist": "Dreg",
      "Rarity": "Uncommon",
      "id": "OTK079",
      "Description": "Toughness 9.\n(Slot >2)[Kill]: Each ally in the first 3 slots Heals 24."
    },
    {
      "Number": 80,
      "Name": "Maria Debeaumont",
      "CardType": "Character",
      "Faction": "Owner",
      "Gender": "Female",
      "Artist": "Daniel Vega",
      "Rarity": "Uncommon",
      "id": "OTK080",
      "Description": "Leftmost [M] ally gets Toughness 12.\n(Owner 3): Rival gets -4x[M] ATK."
    },
    {
      "Number": 81,
      "Name": "Petrorian",
      "CardType": "Character",
      "Faction": "Owner",
      "Gender": "Male",
      "Artist": "Felipe Araya",
      "Rarity": "Uncommon",
      "id": "OTK081",
      "Description": "(Loyal): Leftmost [M] ally gets Toughness 9.\n[Dies]: [M] allies get +10 ATK."
    },
    {
      "Number": 82,
      "Name": "Tadashi",
      "CardType": "Character",
      "Faction": "Owner",
      "Gender": "Male",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Uncommon",
      "id": "OTK082",
      "Description": "Leftmost [F] ally gets +62 ATK.\n(Armed)[Fight step]: Gets +5x[F] ATK. Then, hit assigned Tech."
    },
    {
      "Number": 83,
      "Name": "Gaby & Freya",
      "CardType": "Character",
      "Faction": "Owner",
      "Gender": "Female",
      "Artist": "Sara Contreras",
      "Rarity": "Uncommon",
      "id": "OTK083",
      "Description": "[Attack]: Gets -5 ATK.\n[Kill]: Gets +10x[F] ATK."
    },
    {
      "Number": 84,
      "Name": "Mr. Dunkel",
      "CardType": "Character",
      "Faction": "Owner",
      "Gender": "Male",
      "Artist": "Sergio Lantadilla",
      "Rarity": "Uncommon",
      "id": "OTK084",
      "Description": "[Attack]: Rightmost foe Obeys.\n(Loyal) [Draw step]: Up to 3 allies to the left Heal 8."
    },
    {
      "Number": 85,
      "Name": "Peshmerga Rebel Cell",
      "CardType": "Character",
      "Faction": "Undeviant",
      "Gender": "Non Binary",
      "Artist": "Gonzo Snow",
      "Rarity": "Uncommon",
      "id": "OTK085",
      "Description": "Toughness 12+[NB].\n[Arrive]: Riots 1 to the right."
    },
    {
      "Number": 86,
      "Name": "Shinjuku Gang",
      "CardType": "Character",
      "Faction": "Undeviant",
      "Gender": "Non Binary",
      "Artist": "Javiera D\u00edaz",
      "Rarity": "Uncommon",
      "id": "OTK086",
      "Description": "[Fight step]: Frightens rival."
    },
    {
      "Number": 87,
      "Name": "Hired Ops Team",
      "CardType": "Character",
      "Faction": "Undeviant",
      "Gender": "Non Binary",
      "Artist": "Carlos Moreno",
      "Rarity": "Uncommon",
      "id": "OTK087",
      "Description": "Berserk. Toughness 5x[NB].\n[Arrive]: Hit leftmost opposing Tech once. Repeat this process for each different Faction among allies."
    },
    {
      "Number": 88,
      "Name": "Lt. Krammerman",
      "CardType": "Character",
      "Faction": "Undeviant",
      "Gender": "Female",
      "Artist": "Alexia O\u00f1ate",
      "Rarity": "Uncommon",
      "id": "OTK088",
      "Description": "Toughness 2x[F].\n[Struck]: Deal 2x[F] damage to the rival."
    },
    {
      "Number": 89,
      "Name": "Giuseppe Mori",
      "CardType": "Character",
      "Faction": "Undeviant",
      "Gender": "Male",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Uncommon",
      "id": "OTK089",
      "Description": "Gets +[M]x[M] ATK.\n[Kill]: Heals 100."
    },
    {
      "Number": 90,
      "Name": "Adil Nasseri",
      "CardType": "Character",
      "Faction": "Undeviant",
      "Gender": "Male",
      "Artist": "Patricio Araya",
      "Rarity": "Uncommon",
      "id": "OTK090",
      "Description": "(HP>25%): Foes adjacent to rival both get -45 HP and rightmost foe gets -40 ATK."
    },
    {
      "Number": 91,
      "Name": "Cassie Hayes",
      "CardType": "Character",
      "Faction": "Undeviant",
      "Gender": "Female",
      "Artist": "Rowein",
      "Rarity": "Uncommon",
      "id": "OTK091",
      "Description": "(Rightmost): Whenever an ally [Dies], your leftmost [F] ally gets +13 ATK.\n[Arrive]: Rival Obeys."
    },
    {
      "Number": 92,
      "Name": "Clockdown",
      "CardType": "Character",
      "Faction": "Awaken",
      "Gender": "Male",
      "Artist": "Koi",
      "Rarity": "Common",
      "id": "OTK092",
      "Description": "Gets +10x[M] ATK.\n[Arrive]: Leftmost Entropy and leftmost Awaken allies both get +6x(AwakenxEntropy) HP."
    },
    {
      "Number": 93,
      "Name": "Vole",
      "CardType": "Character",
      "Faction": "Awaken",
      "Gender": "Non Binary",
      "Artist": "Daniel Vega",
      "Rarity": "Common",
      "id": "OTK093",
      "Description": "Textless"
    },
    {
      "Number": 94,
      "Name": "Starry Louise",
      "CardType": "Character",
      "Faction": "Awaken",
      "Gender": "Female",
      "Artist": "Javiera D\u00edaz",
      "Rarity": "Common",
      "id": "OTK094",
      "Description": "[F] allies get Toughness 9.\n(Loyal)[Dies]: Ally with the lowest ATK gets +40 ATK. "
    },
    {
      "Number": 95,
      "Name": "Weye Tahiel",
      "CardType": "Character",
      "Faction": "Awaken",
      "Gender": "Non Binary",
      "Artist": "Dreg",
      "Rarity": "Common",
      "id": "OTK095",
      "Description": "Toughness 10+(AwakenxInhuman).\n[NB] allies get +9+Awaken+Inhuman ATK."
    },
    {
      "Number": 96,
      "Name": "Kelsey K",
      "CardType": "Character",
      "Faction": "Awaken",
      "Gender": "Female",
      "Artist": "Daniel Vega",
      "Rarity": "Common",
      "id": "OTK096",
      "Description": "Leftmost [F] ally gets +10x[F] ATK.\n[Attack]: Your rightmost Tech gets +1 RES."
    },
    {
      "Number": 97,
      "Name": "Feste",
      "CardType": "Character",
      "Faction": "Awaken",
      "Gender": "Non Binary",
      "Artist": "Tae Valenzuela",
      "Rarity": "Common",
      "id": "OTK097",
      "Description": "Toughness 4x[NB].\n[Arrive]: Gets +12/+5 for each [F] and [M] foe."
    },
    {
      "Number": 98,
      "Name": "Lexie",
      "CardType": "Character",
      "Faction": "Entropy",
      "Gender": "Female",
      "Artist": "Daniel Vega",
      "Rarity": "Common",
      "id": "OTK098",
      "Description": "Entropy allies get Toughness 4x(Awaken+Inhuman+Owner).\n[Arrive]: Awaken allies get +4xEntropy ATK. Inhuman allies get +8xEntropy HP. Owner allies Heal 11xEntropy."
    },
    {
      "Number": 99,
      "Name": "Eryn Eryn",
      "CardType": "Character",
      "Faction": "Entropy",
      "Gender": "Male",
      "Artist": "Carlos Moreno",
      "Rarity": "Common",
      "id": "OTK099",
      "Description": "Entropy allies get Toughness 5xInhuman.\n(Slot>1)[Struck]: Riots 2 to the right."
    },
    {
      "Number": 100,
      "Name": "Amir Elnaiem",
      "CardType": "Character",
      "Faction": "Entropy",
      "Gender": "Non Binary",
      "Artist": "Rowein",
      "Rarity": "Common",
      "id": "OTK100",
      "Description": "Textless"
    },
    {
      "Number": 101,
      "Name": "Ryder Dallas",
      "CardType": "Character",
      "Faction": "Entropy",
      "Gender": "Male",
      "Artist": "Gonzo Snow",
      "Rarity": "Common",
      "id": "OTK101",
      "Description": "Toughness 10.\nOther rightmost [M] ally gets +29 ATK. \nOther leftmost Entropy ally gets +29 ATK."
    },
    {
      "Number": 102,
      "Name": "Milly & Gilly",
      "CardType": "Character",
      "Faction": "Entropy",
      "Gender": "Non Binary",
      "Artist": "Catalina Carlesi",
      "Rarity": "Common",
      "id": "OTK102",
      "Description": "(Entropy allies =2): Entropy allies get Toughness 22 and [NB] allies get +23 ATK.\n(Slot <3)[Struck]: Rightmost ally Riots 2 to the right."
    },
    {
      "Number": 103,
      "Name": "Jerick",
      "CardType": "Character",
      "Faction": "Entropy",
      "Gender": "Male",
      "Artist": "Daniel Vega",
      "Rarity": "Common",
      "id": "OTK103",
      "Description": "[Arrive]: If rival has higher ATK than Jerick, they get -30 ATK.\n[Attack]: Deals 3 damage to opposing HQ for each foe that is [F] or [NB]. "
    },
    {
      "Number": 104,
      "Name": "Josie Sankoh",
      "CardType": "Character",
      "Faction": "Inhuman",
      "Gender": "Male",
      "Artist": "Daniel Vega",
      "Rarity": "Common",
      "id": "OTK104",
      "Description": "[Dev step]: Rival gets -5 ATK."
    },
    {
      "Number": 105,
      "Name": "Mubarak",
      "CardType": "Character",
      "Faction": "Inhuman",
      "Gender": "Non Binary",
      "Artist": "Dreg",
      "Rarity": "Common",
      "id": "OTK105",
      "Description": "[NB] allies get Toughness 8.\n[Kill]: [NB] allies get +12 ATK."
    },
    {
      "Number": 106,
      "Name": "Al-Hafeez",
      "CardType": "Character",
      "Faction": "Inhuman",
      "Gender": "Male",
      "Artist": "Daniel Vega",
      "Rarity": "Common",
      "id": "OTK106",
      "Description": "Textless"
    },
    {
      "Number": 107,
      "Name": "Vex Nation",
      "CardType": "Character",
      "Faction": "Inhuman",
      "Gender": "Non Binary",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Common",
      "id": "OTK107",
      "Description": "[Arrive]: Frightens foe in Slot 1.\n[Arrive] or [Dies]: Hits each opposing Tech once."
    },
    {
      "Number": 108,
      "Name": "Lenny Boi",
      "CardType": "Character",
      "Faction": "Inhuman",
      "Gender": "Male",
      "Artist": "Sergio Lantadilla",
      "Rarity": "Common",
      "id": "OTK108",
      "Description": "Inhuman allies get Toughness 6+Owner.\n[Fight step]: If there's an Owner ally in Slot 1, Frighten their rival."
    },
    {
      "Number": 109,
      "Name": "The Jackals",
      "CardType": "Character",
      "Faction": "Inhuman",
      "Gender": "Non Binary",
      "Artist": "Patricio Araya",
      "Rarity": "Common",
      "id": "OTK109",
      "Description": "Gets (+4/+10)x[NB].\n(Loyal)[Fight step]: If rival is Awaken, they get -10 ATK. Then, Frighten them."
    },
    {
      "Number": 110,
      "Name": "Jasper",
      "CardType": "Character",
      "Faction": "Owner",
      "Gender": "Male",
      "Artist": " Daniel Vega",
      "Rarity": "Common",
      "id": "OTK110",
      "Description": "Textless"
    },
    {
      "Number": 111,
      "Name": "Sphynx",
      "CardType": "Character",
      "Faction": "Owner",
      "Gender": "Female",
      "Artist": "Dreg",
      "Rarity": "Common",
      "id": "OTK111",
      "Description": "[Arrive]: Deals 5x[F] damage to every [M] and [NB] foe."
    },
    {
      "Number": 112,
      "Name": "Fyodor Volkov",
      "CardType": "Character",
      "Faction": "Owner",
      "Gender": "Male",
      "Artist": "Dreg",
      "Rarity": "Common",
      "id": "OTK112",
      "Description": "Awaken allies get (+11/+19)xOwner.\n(Awaken 3): Owner allies get Toughness 4xAwaken."
    },
    {
      "Number": 113,
      "Name": "Junichiro",
      "CardType": "Character",
      "Faction": "Owner",
      "Gender": "Non Binary",
      "Artist": "Daniel Vega",
      "Rarity": "Common",
      "id": "OTK113",
      "Description": "(Loyal): Gets Toughness 8.\n[Kill]: Gets +4xNB ATK."
    },
    {
      "Number": 114,
      "Name": "Reinhold",
      "CardType": "Character",
      "Faction": "Owner",
      "Gender": "Male",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Common",
      "id": "OTK114",
      "Description": "Toughness 19.\n(Armed): Gets +30xRES HP.\n"
    },
    {
      "Number": 115,
      "Name": "Qui Long",
      "CardType": "Character",
      "Faction": "Owner",
      "Gender": "Male",
      "Artist": "Daniel Vega",
      "Rarity": "Common",
      "id": "OTK115",
      "Description": "[Arrive]: Up to 2 allies to the left get +20 ATK.\n(Loyal) [Arrive]: If the leftmost foe is Entropy, they get -22 ATK. "
    },
    {
      "Number": 116,
      "Name": "Rahmi",
      "CardType": "Character",
      "Faction": "Undeviant",
      "Gender": "Male",
      "Artist": "Daniel Vega",
      "Rarity": "Common",
      "id": "OTK116",
      "Description": "(Armed): Gets +10xRES ATK.\n(Slot <3)[Attack]: Up to 3 allies to the right get +13 ATK each."
    },
    {
      "Number": 117,
      "Name": "Leon Radi\u0107",
      "CardType": "Character",
      "Faction": "Undeviant",
      "Gender": "Male",
      "Artist": "Thor",
      "Rarity": "Common",
      "id": "OTK117",
      "Description": "As long as rival has Basic Attack Type, they get -25 ATK.\nRival and adjacent foes get -45 HP."
    },
    {
      "Number": 118,
      "Name": "Ottavia Ricci",
      "CardType": "Character",
      "Faction": "Undeviant",
      "Gender": "Female",
      "Artist": "Javier Bahamonde",
      "Rarity": "Common",
      "id": "OTK118",
      "Description": "[Struck]: Regardless of Ottavia Ricci's planning, adjacent allies Heal 11.\n[Dies]: Allies Heal 31."
    },
    {
      "Number": 119,
      "Name": "Sargento C\u00e1rdenas",
      "CardType": "Character",
      "Faction": "Undeviant",
      "Gender": "Male",
      "Artist": "Gonzo Snow",
      "Rarity": "Common",
      "id": "OTK119",
      "Description": "Textless"
    },
    {
      "Number": 120,
      "Name": "Clayton Harris, P.I",
      "CardType": "Character",
      "Faction": "Undeviant",
      "Gender": "Male",
      "Artist": "Daniel Vega",
      "Rarity": "Common",
      "id": "OTK120",
      "Description": "[Arrive]: Characters with Blast Attack Type get -30 ATK."
    },
    {
      "Number": 121,
      "Name": "Arthur LaRue",
      "CardType": "Character",
      "Faction": "Undeviant",
      "Gender": "Male",
      "Artist": "Rowein",
      "Rarity": "Common",
      "id": "OTK121",
      "Description": "Textless"
    },
    {
      "Number": 122,
      "Name": "Cisneros",
      "CardType": "Character",
      "Faction": "Undeviant",
      "Gender": "Non Binary",
      "Artist": "Daniel Vega",
      "Rarity": "Common",
      "id": "OTK122",
      "Description": "[Attack]: The 2 leftmost foes get -16 ATK each."
    },
    {
      "Number": 123,
      "Name": "Lyudmila",
      "CardType": "Technology",
      "Faction": "Awaken",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Legendary",
      "id": "OTK123",
      "Description": "User gets +50 ATK. As long as the user has Ranged Attack Type, they add +2 to their Range.\n[Drop]: Deal 48 damage to the rightmost foe."
    },
    {
      "Number": 124,
      "Name": "Airshutter",
      "CardType": "Technology",
      "Faction": "Awaken",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Legendary",
      "id": "OTK124",
      "Description": "User gets +9xAwaken ATK.\n(Loyal)[Attack]: Deals 30 damage to the opposing HQ."
    },
    {
      "Number": 125,
      "Name": "The Panther",
      "CardType": "Technology",
      "Faction": "Entropy",
      "Artist": "Gonzo Snow",
      "Rarity": "Legendary",
      "id": "OTK125",
      "Description": "User gets Toughness 7 and +36 ATK.\n(Loyal): Entropy allies get Toughness 2 and +5 ATK."
    },
    {
      "Number": 126,
      "Name": "Oathmaker",
      "CardType": "Technology",
      "Faction": "Entropy",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Legendary",
      "id": "OTK126",
      "Description": "(Loyal)[Draw step]: If General Planning is 0, deals 3xEntropy damage to the opposing HQ.\n[End step]: If General Planning is 0, user gets +4xEntropy ATK. Then, Riots 1 to the left."
    },
    {
      "Number": 127,
      "Name": "St. Trophime",
      "CardType": "Technology",
      "Faction": "Inhuman",
      "Artist": "Alexia O\u00f1ate",
      "Rarity": "Legendary",
      "id": "OTK127",
      "Description": "[Fight- step]: User gets +5xInhuman ATK. Hit this Tech once. "
    },
    {
      "Number": 128,
      "Name": "Azrael's Needles",
      "CardType": "Technology",
      "Faction": "Inhuman",
      "Artist": "Felipe Araya",
      "Rarity": "Legendary",
      "id": "OTK128",
      "Description": "User gets +17 ATK.\n[End step]: If General Planning is 0, deal 40 Damage to the rightmost foe."
    },
    {
      "Number": 129,
      "Name": "Watchbear",
      "CardType": "Technology",
      "Faction": "Owner",
      "Artist": "Felipe Araya",
      "Rarity": "Legendary",
      "id": "OTK129",
      "Description": "Automated. User gets +15/+60.\n(Slot <3)[Draw step]: Deals 45 damage to the rival.\n"
    },
    {
      "Number": 130,
      "Name": "Mother",
      "CardType": "Technology",
      "Faction": "Owner",
      "Artist": "Gonzo Snow",
      "Rarity": "Legendary",
      "id": "OTK130",
      "Description": "Automated. User gets +30 ATK.\n[Dev step]:If General Planning is 0, the most wounded foe Obeys."
    },
    {
      "Number": 131,
      "Name": "Temazcal",
      "CardType": "Technology",
      "Faction": "Awaken",
      "Artist": "Gonzo Snow",
      "Rarity": "Rare",
      "id": "OTK131",
      "Description": "Automated. User gets +88 ATK.\n[Arrive]: If General Planning is 0, Characters Heal 60."
    },
    {
      "Number": 132,
      "Name": "Dancing Dazer",
      "CardType": "Technology",
      "Faction": "Awaken",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Rare",
      "id": "OTK132",
      "Description": "Automated. User gets +120 HP.\n[Draw step]: If General Planning is 0, Characters get +5 ATK."
    },
    {
      "Number": 133,
      "Name": "Bloodsuckers",
      "CardType": "Technology",
      "Faction": "Entropy",
      "Artist": "Dreg",
      "Rarity": "Rare",
      "id": "OTK133",
      "Description": "Automated. User gets +42 ATK and rival gets -40 HP.\n[Struck]: Deals 40 Damage to the rival.\n"
    },
    {
      "Number": 134,
      "Name": "Dethroner",
      "CardType": "Technology",
      "Faction": "Entropy",
      "Artist": "Genzo",
      "Rarity": "Rare",
      "id": "OTK134",
      "Description": "Grip. User gets Toughness 9+Entropy and +18+Entropy ATK.\n"
    },
    {
      "Number": 135,
      "Name": "Double Boomer",
      "CardType": "Technology",
      "Faction": "Inhuman",
      "Artist": "Felipe Araya",
      "Rarity": "Rare",
      "id": "OTK135",
      "Description": "[End step]: If General Planning is 0, deal 45 damage to the opposing HQ."
    },
    {
      "Number": 136,
      "Name": "B-37 Razer",
      "CardType": "Technology",
      "Faction": "Inhuman",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Rare",
      "id": "OTK136",
      "Description": "User gets Toughness 25 and +100 HP.\n[Pick-up]: User gets +17 ATK."
    },
    {
      "Number": 137,
      "Name": "Stinger",
      "CardType": "Technology",
      "Faction": "Owner",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Rare",
      "id": "OTK137",
      "Description": "Automated. User gets +32 ATK.\n[Dev step]: If General Planning is 0, deal 22 damage to the rival.\n"
    },
    {
      "Number": 138,
      "Name": "MS-021",
      "CardType": "Technology",
      "Faction": "Owner",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Rare",
      "id": "OTK138",
      "Description": "User gets Grip and Toughness 27. Adjacent allies get Toughness 9."
    },
    {
      "Number": 139,
      "Name": "Time Waster",
      "CardType": "Technology",
      "Faction": "Awaken",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Uncommon",
      "id": "OTK139",
      "Description": "Automated. User gets +80 HP.\n[Arrive]: Deals 4xAwaken damage to each foe."
    },
    {
      "Number": 140,
      "Name": "Fast Map Toolkit",
      "CardType": "Technology",
      "Faction": "Awaken",
      "Artist": "Sara Contreras",
      "Rarity": "Uncommon",
      "id": "OTK140",
      "Description": "Rival gets -25 ATK.\n[Pick up]: Gets +1 RES.\n[Dev step]: User gets +5xRES ATK."
    },
    {
      "Number": 141,
      "Name": "Yellow Battleflag",
      "CardType": "Technology",
      "Faction": "Entropy",
      "Artist": "Patricio Araya",
      "Rarity": "Uncommon",
      "id": "OTK141",
      "Description": "User gets +200 HP.\n(Loyal & Entropy 3): Whenever a foe dies, your Entropy allies get +9 ATK."
    },
    {
      "Number": 142,
      "Name": "Darkling Rover",
      "CardType": "Technology",
      "Faction": "Entropy",
      "Artist": "Carlos Moreno",
      "Rarity": "Uncommon",
      "id": "OTK142",
      "Description": "User gets Toughness 16 and +8xEntropy ATK."
    },
    {
      "Number": 143,
      "Name": "First Grader",
      "CardType": "Technology",
      "Faction": "Inhuman",
      "Artist": "Carlos Moreno",
      "Rarity": "Uncommon",
      "id": "OTK143",
      "Description": "User gets +75 ATK. \n[Attack]: User gets -10 ATK. Hit this Tech once.\n"
    },
    {
      "Number": 144,
      "Name": "Bull-Up 3x",
      "CardType": "Technology",
      "Faction": "Inhuman",
      "Artist": "Daniel Vega",
      "Rarity": "Uncommon",
      "id": "OTK144",
      "Description": "User gets Berserk and +35 HP.\n(Loyal): User gets Toughness 2xInhuman and +35 HP."
    },
    {
      "Number": 145,
      "Name": "Spy-flies",
      "CardType": "Technology",
      "Faction": "Owner",
      "Artist": "Carlos Moreno",
      "Rarity": "Uncommon",
      "NFT Serial #": 0,
      "id": "OTK145",
      "Description": "Automated. As long as rival is not Owner, user gets +64 ATK.\n(Loyal): Rival gets -55 ATK."
    },
    {
      "Number": 146,
      "Name": "C-14",
      "CardType": "Technology",
      "Faction": "Owner",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Uncommon",
      "id": "OTK146",
      "Description": "User gets Toughness 19.\n(Slot <3): User gets +35 ATK."
    },
    {
      "Number": 147,
      "Name": "Lucky Bento Box",
      "CardType": "Technology",
      "Faction": "Undeviant",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Uncommon",
      "id": "OTK147",
      "Description": "[Dev step]: [NB] allies Heal 8.\n(User's HP<80%)[End step]: User Heals 60. Hit this Tech once."
    },
    {
      "Number": 148,
      "Name": "Escape Pod",
      "CardType": "Technology",
      "Faction": "Undeviant",
      "Artist": "Javier Bahamonde",
      "Rarity": "Uncommon",
      "id": "OTK148",
      "Description": "As long as user is [M], he gets +22 ATK.\n(User's HP<25%)[Pick-up] or [Fight step]: User Heals 120. Hit this Tech once."
    },
    {
      "Number": 149,
      "Name": "Enhanced Taser",
      "CardType": "Technology",
      "Faction": "Undeviant",
      "Artist": "Javier Bahamonde",
      "Rarity": "Uncommon",
      "id": "OTK149",
      "Description": "As long as user is [F], she gets +35 ATK.  \n[Pick-up]: User Frightens rival."
    },
    {
      "Number": 150,
      "Name": "Lobotomizer",
      "CardType": "Technology",
      "Faction": "Awaken",
      "Artist": "Daniel Vega",
      "Rarity": "Common",
      "id": "OTK150",
      "Description": "User gets Grip and +100 HP.\n[End step]: Hit the rightmost opposing Tech once. Repeat.\n[Destroy]: Gets -1 RES."
    },
    {
      "Number": 151,
      "Name": "Modular Leech",
      "CardType": "Technology",
      "Faction": "Awaken",
      "Artist": "Manuel Rivera",
      "Rarity": "Common",
      "id": "OTK151",
      "Description": "Automated. Rival gets -35 ATK. \n(Loyal): User gets +20/+30."
    },
    {
      "Number": 152,
      "Name": "Lysso's Eyes",
      "CardType": "Technology",
      "Faction": "Entropy",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Common",
      "id": "OTK152",
      "Description": "User gets Grip and +55/+30.\n(Loyal): Armed Entropy allies get +20/+10."
    },
    {
      "Number": 153,
      "Name": "Retirement Plan",
      "CardType": "Technology",
      "Faction": "Entropy",
      "Artist": "Gonzo Snow",
      "Rarity": "Common",
      "id": "OTK153",
      "Description": "Automated. User gets +60 ATK.\n[Struck]: Deal 120 damage to the rival.\n"
    },
    {
      "Number": 154,
      "Name": "Acid Tank",
      "CardType": "Technology",
      "Faction": "Inhuman",
      "Artist": "Daniel Vega",
      "Rarity": "Common",
      "id": "OTK154",
      "Description": "Automated. User gets Toughness 10.\n(Inhuman 3): Foes get -10 ATK."
    },
    {
      "Number": 155,
      "Name": "Yaba",
      "CardType": "Technology",
      "Faction": "Inhuman",
      "Artist": "Romina Cares",
      "Rarity": "Common",
      "id": "OTK155",
      "Description": "User gets Toughness 21 and +64 ATK."
    },
    {
      "Number": 156,
      "Name": "Red Council",
      "CardType": "Technology",
      "Faction": "Owner",
      "Artist": "Gustavo Lara",
      "Rarity": "Common",
      "id": "OTK156",
      "Description": "Automated. Owner allies get +15 HP.\n(Loyal & Slot 1): User gets +8xOwner ATK."
    },
    {
      "Number": 157,
      "Name": "Scarlet Strainer",
      "CardType": "Technology",
      "Faction": "Owner",
      "Artist": "Javier Bahamonde",
      "Rarity": "Common",
      "id": "OTK157",
      "Description": "Automated. User gets +60 HP.\n[Draw step]: If there's an opposing Tech in Scarlet Strainer's Slot, hit both Techs once."
    },
    {
      "Number": 158,
      "Name": "Kevlar",
      "CardType": "Technology",
      "Faction": "Undeviant",
      "Artist": "Dreg",
      "Rarity": "Common",
      "id": "OTK158",
      "Description": "User gets Grip and Toughness 28."
    },
    {
      "Number": 159,
      "Name": "Home Stereo",
      "CardType": "Technology",
      "Faction": "Undeviant",
      "Artist": "Felipe Araya",
      "Rarity": "Common",
      "id": "OTK159",
      "Description": "[Draw step] or [End step]: User deals 25 Damage to the rightmost foe."
    },
    {
      "Number": 160,
      "Name": "Bull Spikes",
      "CardType": "Technology",
      "Faction": "Undeviant",
      "Artist": "Pamela Meza",
      "Rarity": "Common",
      "id": "OTK160",
      "Description": "Automated. \n[Drop]: Deals 65 damage to the rival. Hit this Tech once.\n[Struck]: Deals 60 damage to the rival."
    },
    {
      "Number": 161,
      "Name": "Molotov Cocktail",
      "CardType": "Technology",
      "Faction": "Undeviant",
      "Artist": "Jos\u00e9 Huicham\u00e1n",
      "Rarity": "Common",
      "id": "OTK161",
      "Description": "[Attack]: Rival and adjacent foes get -8xRES ATK. Hit this Tech once."
    },
    {
      "Number": 162,
      "Name": "Tacos",
      "CardType": "Technology",
      "Faction": "Undeviant",
      "Artist": "Catalina Carlesi",
      "Rarity": "Common",
      "id": "OTK162",
      "Description": "(User's HP<40%)[Pick-up]: User Heals 75. Hit this Tech once.\n(User's HP<30%)[End step]: User Heals 40. Hit this Tech once."
    },
    {
      "Number": 163,
      "Name": "Panopticon",
      "CardType": "Technology",
      "Faction": "Undeviant",
      "Artist": "Sebasti\u00e1n Franchini",
      "Rarity": "Common",
      "id": "OTK163",
      "Description": "Automated. User gets Grip and +90 HP.\nAllies with Ranged Attack Type add +1 to their Range."
    },
    {
      "Number": 164,
      "Name": "Tear Gas Launcher",
      "CardType": "Technology",
      "Faction": "Undeviant",
      "Artist": "Gustavo Lara",
      "Rarity": "Common",
      "id": "OTK164",
      "Description": "[Attack]: Each foe gets -8 ATK. Hit this Tech once."
    }
  ]